# Generated by Django 5.2.14 on 2026-05-08 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('meal_name', models.CharField(default='Signature Meal', max_length=100)),
                ('description', models.TextField(default='A delicious signature dish.')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=500')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
