# Generated by Django 5.2.14 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
