# Generated by Django 5.2.14 on 2026-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1996/1996055.png'),
        ),
    ]
